# Generated by Django 4.1.3 on 2023-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table19812021Tmax',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('region', models.BigIntegerField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_1981-2021_tmax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table19812021Tmin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('region', models.BigIntegerField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_1981-2021_tmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table19812021Rr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('region', models.BigIntegerField(blank=True, null=True)),
                ('precip', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_1981-2021_rr',
                'managed': True,
            },
        ),
    ]
